<?php
// COMMON
require_once $system_path . 'core/Model.php';

require_once APPPATH . 'models/repositories/_RepositoryConst.php';
require_once APPPATH . 'models/repositories/BaseRepository.php';
require_once APPPATH . 'models/repositories/CategoryRepository.php';
require_once APPPATH . 'models/repositories/CommentRepository.php';
require_once APPPATH . 'models/repositories/ObjectRepository.php';
require_once APPPATH . 'models/repositories/PostRepository.php';
require_once APPPATH . 'models/repositories/PostTagRepository.php';
require_once APPPATH . 'models/repositories/SettingRepository.php';
require_once APPPATH . 'models/repositories/TagRepository.php';
require_once APPPATH . 'models/repositories/UserRepository.php';
require_once APPPATH . 'models/repositories/FileRepository.php';
require_once APPPATH . 'models/repositories/UserSessionRepository.php';
require_once APPPATH . 'models/repositories/ProfileDetailRepository.php';
require_once APPPATH . 'models/repositories/ProfileRepository.php';
require_once APPPATH . 'models/repositories/SupportTicketRepository.php';
require_once APPPATH . 'models/repositories/TeethGrowRepository.php';
require_once APPPATH . 'models/repositories/SessionRepository.php';
require_once APPPATH . 'models/repositories/AnswerRepository.php';
require_once APPPATH . 'models/repositories/QuestionRepository.php';



