<?php
require_once APPPATH . 'models/serivces/FileService.php';
require_once APPPATH . 'models/serivces/MailService.php';
require_once APPPATH . 'models/serivces/RegistorServices.php';
require_once APPPATH . 'models/serivces/TicketSupport.php';
require_once APPPATH . 'models/serivces/ServiceFactory.php';
require_once APPPATH . 'models/serivces/ExportService.php';
require_once APPPATH . 'models/serivces/TimeService.php';
require_once APPPATH . 'models/serivces/ReportService.php';
require_once APPPATH . 'models/serivces/ReportOneUserService.php';
require_once APPPATH . 'models/serivces/CategoryService.php';



