<?php
	/* SETTINGS START */

$themeSettings = array(
'bar_background' => '#0F75BB',
'bar_gradient_start' => '#0F75BB',
'bar_gradient_end' => '#0F75BB',
'bar_border' => '#CCCCCC',
'bar_color' => '#333333',
'bar_color_disabled' => '#4D4D4F',
'bar_border_light' => '#E5E5E5',
'bar_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'bar_font_size' => '11px',
'bar_text_background' => '#FFFFFF',
'tab_background' => '#FFFFFF',
'tab_color' => '#4D4D4F',
'tab_border' => '#0F75BB',
'tab_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tab_font_size' => '11px',
'tab_font_size_small' => '10px',
'tab_color_self' => '#333333',
'tab_title_color' => '#FFFFFF',
'tab_title_backgroud_light' => '#D8F8FF',
'tab_title_background' => '#D8F8FF',
'tab_title_gradient_start' => '#61CADF',
'tab_title_gradient_end' => '#61CADF',
'tab_title_border' => '#3FABBE',
'tab_title_font_family' => 'Tahoma,Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tab_title_font_size' => '11px',
'tab_title_font_size_large' => '12px',
'tab_title_text_background' => '#0F75BB',
'tab_sub_background' => '#EEEEEE',
'tab_sub_color' => '#666666',
'tab_border_light' => '#CCCCCC',
'tab_border_lighter' => '#EEEEEE',
'tooltip_background' => '#0F75BB',
'tooltip_color' => '#FFFFFF',
'tooltip_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tooltip_font_size' => '11px',
'tooltip_break' => '#666666',
'tab_link_color' => '#0F75BB',
);

/* SETTINGS END */
  
